name: qubah_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  # sdk: '>=3.4.4 <4.0.0'
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  equatable: ^2.0.5
  get_storage: ^2.1.1
  camera: ^0.10.5+9
  shimmer: ^3.0.0
  get: 4.6.6
  flutter: 
    sdk: flutter
  geolocator: ^11.1.0
  geocoding: ^3.0.0
  lottie: ^3.1.2

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

