// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp1RovGIiZ5dn1ZFvv4GE7T50GNt1YqAI',
    appId: '1:445254866282:web:f79b8ee39f68998aabc113',
    messagingSenderId: '445254866282',
    projectId: 'qubah-6f71c',
    authDomain: 'qubah-6f71c.firebaseapp.com',
    storageBucket: 'qubah-6f71c.appspot.com',
    measurementId: 'G-K5FM1HK1ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAasgTXhkIEaS4IC1RzV-cqdJe-OoEdwtQ',
    appId: '1:445254866282:android:d7db3af0d16736b9abc113',
    messagingSenderId: '445254866282',
    projectId: 'qubah-6f71c',
    storageBucket: 'qubah-6f71c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOcO8nktntpJ9qUYNDXiVL0eNkVQ5WzgA',
    appId: '1:445254866282:ios:4e28650314221eb9abc113',
    messagingSenderId: '445254866282',
    projectId: 'qubah-6f71c',
    storageBucket: 'qubah-6f71c.appspot.com',
    iosBundleId: 'com.example.qubahApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOcO8nktntpJ9qUYNDXiVL0eNkVQ5WzgA',
    appId: '1:445254866282:ios:4e28650314221eb9abc113',
    messagingSenderId: '445254866282',
    projectId: 'qubah-6f71c',
    storageBucket: 'qubah-6f71c.appspot.com',
    iosBundleId: 'com.example.qubahApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp1RovGIiZ5dn1ZFvv4GE7T50GNt1YqAI',
    appId: '1:445254866282:web:4e1081a39398bbeaabc113',
    messagingSenderId: '445254866282',
    projectId: 'qubah-6f71c',
    authDomain: 'qubah-6f71c.firebaseapp.com',
    storageBucket: 'qubah-6f71c.appspot.com',
    measurementId: 'G-0KE9LT9MTR',
  );
}
